"""Recursos compartidos: animaciones, fuentes, imágenes referenciadas por código."""

from .AnimacionesPyQt5 import AnimacionesPyQt5
from .LayoutRelativo import LayoutRelativo
from .MixinLayout import MixinLayout

from .DimensionesObjetos import (
    DR_ComponentesBootup_EspacioLogo_A_Titulo_Alto,
    DR_ComponentesBootup_Etiqueta_Titulo_Padding_Alto,
    DR_ComponentesBootup_Etiqueta_Padding_Min,
    DR_ComponentesBootup_Logo_Max,
    DR_ComponentesBootup_Logo_Min,
    DR_ComponentesBootup_OS_Divisor_Ancho_Interior,
    DR_ComponentesBootup_SeparacionLotusOS_Ancho,
    DR_ComponentesBootup_Titulo_Alto,
    DR_ComponentesBootup_Titulo_Ancho,
    DR_OverlayEjemplo_Alto,
    DR_OverlayEjemplo_Ancho,
    DR_ElegirUsuario_Avatar_Tamano,
    DR_ElegirUsuario_Boton_Alto,
    DR_ElegirUsuario_Boton_Ancho_Max,
    DR_ElegirUsuario_Boton_Confirmar_Y,
    DR_ElegirUsuario_Campo_Alto,
    DR_ElegirUsuario_Campo_Ancho,
    DR_ElegirUsuario_Label_Alto,
    DR_ElegirUsuario_Separacion_Botones,
    DR_ElegirUsuario_Separacion_Campos,
    DR_ElegirUsuario_Y_Inicio_Botones,
    DR_ElegirUsuario_Y_Titulo_Crear,
    DR_Carrusel_Avatar_Diametro,
    DR_Carrusel_Avatar_Y,
    DR_Carrusel_Boton_Ingresar_H,
    DR_Carrusel_Boton_Ingresar_W,
    DR_Carrusel_Boton_Ingresar_Y,
    DR_Carrusel_Boton_Nuevo_Alto,
    DR_Carrusel_Boton_Nuevo_Ancho,
    DR_Carrusel_Boton_Nuevo_Y,
    DR_Carrusel_Error_Alto,
    DR_Carrusel_Error_Y,
    DR_Carrusel_Flecha_H,
    DR_Carrusel_Flecha_W,
    DR_Carrusel_Flecha_X_Derecha,
    DR_Carrusel_Flecha_X_Izquierda,
    DR_Carrusel_Flecha_Y,
    DR_Carrusel_Nombre_Alto,
    DR_Carrusel_Nombre_Y,
    DR_Carrusel_PIN_Alto,
    DR_Carrusel_PIN_Ancho,
    DR_Carrusel_PIN_Y,
    DR_Carrusel_Tarjeta_H,
    DR_Carrusel_Tarjeta_W,
    DR_Carrusel_Tarjeta_Y,
)

from .FuentesGothic import (
    GothicBold,
    GothicBoldItalic,
    GothicItalic,
    GothicLight,
    GothicLightItalic,
    GothicMedium,
    GothicMediumItalic,
    GothicNormal,
    GothicSemibold,
    GothicSemiboldItalic,
    GothicThin,
    GothicThinItalic,
)

from .PaletaColores import (
    PC_AzulOSLotus,
    PC_Blanco,
    PC_BordePanel,
    PC_FondoEscritorio,
    PC_GrisTextoClaro,
    PC_Negro,
    PC_Naranja,
    PC_Rojo,
    PC_Transparente,
)

__all__ = [
    "AnimacionesPyQt5",
    "LayoutRelativo",
    "MixinLayout",
    # Paleta de colores
    "PC_AzulOSLotus",
    "PC_Blanco",
    "PC_BordePanel",
    "PC_FondoEscritorio",
    "PC_GrisTextoClaro",
    "PC_Negro",
    "PC_Naranja",
    "PC_Rojo",
    "PC_Transparente",
    #Fuentes de la familia Gothic
    "GothicBold",
    "GothicBoldItalic",
    "GothicItalic",
    "GothicLight",
    "GothicLightItalic",
    "GothicMedium",
    "GothicMediumItalic",
    "GothicNormal",
    "GothicSemibold",
    "GothicSemiboldItalic",
    "GothicThin",
    "GothicThinItalic",
    #Dimensiones de los componentes de la pantalla Bootup
    "DR_ComponentesBootup_EspacioLogo_A_Titulo_Alto",
    "DR_ComponentesBootup_Etiqueta_Titulo_Padding_Alto",
    "DR_ComponentesBootup_Etiqueta_Padding_Min",
    "DR_ComponentesBootup_Logo_Max",
    "DR_ComponentesBootup_Logo_Min",
    "DR_ComponentesBootup_OS_Divisor_Ancho_Interior",
    "DR_ComponentesBootup_SeparacionLotusOS_Ancho",
    "DR_ComponentesBootup_Titulo_Alto",
    "DR_ComponentesBootup_Titulo_Ancho",
    #Dimensiones de la pantalla Overlay Ejemplo
    "DR_OverlayEjemplo_Alto",
    "DR_OverlayEjemplo_Ancho",
    "DR_ElegirUsuario_Boton_Alto",
    "DR_ElegirUsuario_Boton_Ancho_Max",
    "DR_ElegirUsuario_Separacion_Botones",
    "DR_ElegirUsuario_Y_Inicio_Botones",
    "DR_ElegirUsuario_Avatar_Tamano",
    "DR_ElegirUsuario_Campo_Alto",
    "DR_ElegirUsuario_Campo_Ancho",
    "DR_ElegirUsuario_Label_Alto",
    "DR_ElegirUsuario_Y_Titulo_Crear",
    "DR_ElegirUsuario_Separacion_Campos",
    "DR_ElegirUsuario_Boton_Confirmar_Y",
    "DR_Carrusel_Boton_Nuevo_Y",
    "DR_Carrusel_Boton_Nuevo_Alto",
    "DR_Carrusel_Boton_Nuevo_Ancho",
    "DR_Carrusel_Tarjeta_Y",
    "DR_Carrusel_Tarjeta_W",
    "DR_Carrusel_Tarjeta_H",
    "DR_Carrusel_Flecha_X_Izquierda",
    "DR_Carrusel_Flecha_X_Derecha",
    "DR_Carrusel_Flecha_Y",
    "DR_Carrusel_Flecha_W",
    "DR_Carrusel_Flecha_H",
    "DR_Carrusel_Avatar_Diametro",
    "DR_Carrusel_Avatar_Y",
    "DR_Carrusel_Nombre_Y",
    "DR_Carrusel_Nombre_Alto",
    "DR_Carrusel_PIN_Y",
    "DR_Carrusel_PIN_Alto",
    "DR_Carrusel_PIN_Ancho",
    "DR_Carrusel_Error_Y",
    "DR_Carrusel_Error_Alto",
    "DR_Carrusel_Boton_Ingresar_Y",
    "DR_Carrusel_Boton_Ingresar_W",
    "DR_Carrusel_Boton_Ingresar_H",
]
